# Generated by Django 4.0.2 on 2022-02-12 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='image',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
